v4 integration
shireenf-ibm/stackrox pull request #3
Opened 2023-08-06 16:19 UTC by shireenf-ibm

initial diff support (code + first successfully running bats test)

2023-08-08 13:17 UTC, adisos requested changes
a few initial comments, still need to review the tests

2023-08-08 13:17 UTC, adisos commented on roxctl/connectivity-map/cta.go
> +	npguardUtil "github.com/np-guard/netpol-analyzer/pkg/netpol/eval"
I would rename `npguardUtil` to `eval`, and `npguard` to `connlist`

2023-08-08 13:17 UTC, adisos commented on roxctl/connectivity-diff/netpol.go
> +		Short: "(Technology Preview) Report connectivity diff based on two directories of network policies and other resources.",
```suggestion
		Short: "(Technology Preview) Report connectivity diff based on two directories of network policies and workload resources YAML manifests.",
```

2023-08-08 13:17 UTC, adisos commented on roxctl/connectivity-diff/netpol.go
> +		Will write to stdout if no output flags are provided.
```suggestion
		Long: `Based on given two folders containing Kubernetes workloads and network policy YAMLs, will report all differences in allowed connections between the directories. 
		Will write to stdout if no output flags are provided.
```

2023-08-08 13:17 UTC, adisos commented on roxctl/connectivity-diff/cta.go
> +}
I would simplify the output file name to be just `connectivity_diff.txt` instead of involving input file names

2023-08-08 13:18 UTC, adisos commented on roxctl/connectivity-map/cta.go
> +	npguardUtil "github.com/np-guard/netpol-analyzer/pkg/netpol/eval"
another option: `npgeval` and `npgconnlist`

2023-08-08 15:11 UTC, adisos commented on roxctl/connectivity-diff/netpol_test.go
> +			expectedAnalysisError: nil,
should also add expected output here?

2023-08-09 05:54 UTC, shireenf-ibm commented on roxctl/connectivity-diff/netpol_test.go
> +			expectedAnalysisError: nil,
we have other tests on same dirs with expected outputs (lines 115-141 ) (this test actually was added just to see that there are no errors )

2023-08-09 06:12 UTC, shireenf-ibm commented on roxctl/connectivity-diff/cta.go
> +}
done

2023-08-09 06:12 UTC, shireenf-ibm commented on roxctl/connectivity-map/cta.go
> +	npguardUtil "github.com/np-guard/netpol-analyzer/pkg/netpol/eval"
done

2023-08-09 07:36 UTC, closed without merging